### ISSUE TITLE
fix id insertion issues

### ISSUE THREAD

**Issue by uansett** [shnergle/ShnergleAdmin#12]
Cannot manually insert IDs from admin panel - either keep overwrite hack (currently implemented, but quite dangerous) or ignore the id field in the panel.

Temp solution is implemented in every insert query and sets the overwrite to true before, and false after, every query.
`// DEV Hack to work brute force mode
        $this->db_query('SET IDENTITY_INSERT ' . $table . ' ON');`
and 

`// DEV Hack end
        $this->db_query('SET IDENTITY_INSERT ' . $table . ' OFF');`

**Comment by krzd** [comment]
Just not setting the id manually, should already do the trick, shouldn't it? As I see SET IDENTITY_INSERT enables you to manually set the id, but there should not be any need for that, as the generated ids are 'safer'. Or did I get that wrong?

**Comment by uansett** [comment]
Yeah generated ids are much better, but I think if you don't specify an id
in the admin panel, it passes an empty string or something ­ at least it
throws an error about not being able to manually update ids even if you
don't specify one

**Comment by krzd** [comment]
How about changing these lines in controller.php (which should actually be Controller.php):

``` php
function add() {
    $this->columns = $this->db_columns();
    $this->render('edit');
}
```

To this:

``` php
function add() {
    $this->columns = $this->db_columns();
    unset($this->columns[0]);
    $this->render('edit');
}
```

So when adding a new entry the id field is not displayed, therefore no value is passed and so no id column gets passed to the database, not even an empty string.

**Comment by uansett** [comment]
Cool, will add.  thanks

**Comment by uansett** [comment]
Id's removed venue cat. Is working (and so should anything else).
