### ISSUE TITLE
Venue: Move on Map

### ISSUE THREAD

**Issue by krzd** [shnergle/ShnergleAdmin#17]

**Comment by trigger2896** [comment]
Adam - this is now very urgent. Please could you put at front of the queue?

**Comment by krzd** [comment]
OK, will start with a simple implementation. When you click somewhere on the map it would add a new pin. If you press update coordinates it would set the venue to the latest pin.
That should give the required functionality, can make it nicer later.

**Comment by krzd** [comment]
Done, as described...
