### ISSUE TITLE
Show a reported image section (in the top menu)

### ISSUE THREAD

**Issue by trigger2896** [shnergle/ShnergleAdmin#25]
Show all the photos that have been hidden, along with who created them, the users that reported the image and the capacity in which they did it.

Then offer the opportunity to 'process' those reported images by tagging them with one of the following options:
- Offensive Content
- Wrong place
- Brand protection
- Poor photo quality
- Privacy breach

**Comment by krzd** [comment]
What is the result of the tagging?

Answer:
Image should be hidden, just save for later analysis.
